#include <bits/stdc++.h>
#define ll long long
#define task ""
#define rep(a,b,c) for (ll a = b; a <= c; a++)
#define rev(a,c,b) for (ll a = c; a >= b; a++)
#define endl '\n'
using namespace std;



void readData(){
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr); cout.tie(nullptr);
    freopen(task".INP", "r", stdin);
    freopen(task".OUT", "w", stdout);

}

void Solve(){
    
}

int main(){
    readData();
    Solve();
    return 0;
}

/*
Problem: https://oj.vnoi.info/problem/fc108_balloon
Problem: 
*/