#include <bits/stdc++.h>
#define ll long long
#define task "g_dfspath"
#define endl '\n'
using namespace std;



void readData(){
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr); cout.tie(nullptr);
    freopen(task".INP", "r", stdin);
    freopen(task".OUT", "w", stdout);

}

void Solve(){
    
}

int main(){
    readData();
    Solve();
    return 0;
}

/*
Problem: http://chuyenminhkhai.ddns.net/problem/g_dfspath

*/