#include <bits/stdc++.h>

// Typedef
typedef long long ll;
typedef unsigned long long ull;
typedef double db;
typedef long double ld;
typedef pair<ll,ll> ii;
typedef vector<ll> vi;
typedef vector<ii> vii;

// Macro
#define task ""
#define rep(i,a,b) for (ll i = (a); i <= (b); ++i)
#define rev(i,a,b) for (ll i = (a); i >= (b); --i)
#define endl '\n'

using namespace std;

void readData() {
    freopen(task".INP", "r", stdin);
    freopen(task".OUT", "w", stdout);

    // Do something

}

void Solve() {
    // Do something

}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr); cout.tie(nullptr);
    
    readData();
    Solve();
    
    return 0;
}